---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-root-secret
  namespace: minio
spec:
  encryptedData:
    root-password: AgA05hbgYld9met0BylMud6OzpcvyGx+vTw/vUAoZgqiT8N1TMl5H0fVleF/GK7vXdGJevfb0vj52EVhw6xN9Se80i90NHGD/pLur7MlBdmZLd/0i/a1vfHgOq8Uw5rVwyUZrrTcszGWsaJgkwXpE2ozn7CNmknVq3l/1V/pym9yiWPbXLS0gjXnZt0oDIjPKC5n920gLKhQWbLZQ7eodRQX02ofcMun/QyMYuFScV7Zfp5TrMhhpz7jKwOLVJftjGmzjkW72XHAMj2K6fgw9jKq0rWjPv6UpsEkFjVdOHnaPkepOAleAW0+MPzRLa25gCNJlVclrivm31X5sEvanNLiq91cC3qcPLBu4NxHq6vvdaak7GftGIth+lvPP2l4ZaMrcCVHhm0t9+bwLR508vSE3lJ9RfmY1EqPcRaBajqzxLDRT0znWWeB4UEfymL08tXQOA20wifn4wt+9IqbkCHBtJQzfEIWaNe9ZD9akWXj6hb+rlNBfwDy1YpLQm+iHpQOzKg7ubawx3uWndn4/T06xogRQ2Q93fsXaVGtEFzjbh6uELDZ8isDAYQi4tt4aJpNRp89mJrf3loMjPVmVY1hMdCu50rGSgu9M6bKN9gLNbREVsGojIDL9/QPUp3ZjbYnWDq7JTZ4svjYr9ZlRMyZbkNPFFxjeGqUQhQNLD+luF9hBysZKjREbipXXCk8I6XaHIxkCUd5ODa68HAZlcvDdJIxF7c2H1BHR8dECHXN0mNnaGIShBONH5cwuLcOSwo=
    root-user: AgBdSzMBQGfgpPNYjKIrbqK8blS6kR/JXGORCAvD1PXgl9nzFcn5LPTgcnasn1DalTpNS/46UDngbJpOQ9WWji65XF/jsjDQp/tl/6BrLMV+lFBr8z8r5f2zr1w37bWlsrbdzHmWa3CeOFfyiP0w/eF70wg+7Z/G/tPDA5KVxeXBvY5gX7Js3IW+8ZAAxmq5pys+oZKulgulMqoIXnxjJ2gIOWqOA2N6+9oo56i7xMFHy7XVahL/Qq5xy+2xoqit64qvnGu5LSBHPsjcGUk5Vp0Wfay/sRDuUFAxNMSfaXeDiwmeVKkh+Z/+N6AxcZfFoDW//C033ZOEyYtcQ4Af+5EiFE1AlQB9bH58vM/kFMLbGDIIAlsrkte/jHj2LBctx2bA0lPU7lhhrqYbF5jOlisblc+UlzRZxbrFyDjE2w0JDeL9zeusl6u9+HFqdNFI4FZ/fap3uhAQMKkH7RYsx2O1j3u64BnoApI7T+JQUWDL7YUNC21Ri0qfnetRPXh48+eofF0VFr9wI6CypSenfgFroiBDNhd/eGQ73bcNao+xfDcXszmK0ACXJ0mmAibHcEqId96wbYS+n9BvuRDGn3u5GZh0Zf0GSuSgG80HzVmmf2G35V7WJMlkKohOWkz9if2wkHvNGOytSf3gq/aVKl92iCIfD00eFpDBfeUaWui0XsV2rNW4JPbHad36QHvLJpVI2glT7rEIRdMN4nU9WA==
  template:
    metadata:
      name: minio-root-secret
      namespace: minio
