---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-oidc-secret
  namespace: forgejo
spec:
  encryptedData:
    clientSecret: AgCENxIWGhBoUZubw3r7UhphfhW4phT/g0iHIQD5n9pPOIwD/qAp6rO2J/99UCluhhyKjB3BmtZ3shN5C7KhCt0AkqA/DKwpLIIDU8zzYipj5OKD4u/VoipCe7u8kJ1MLLeDdGCJ8PGKvJkfQbJFY7b4+b5tQUGlZr3+ekcQeOuifdPGt4P0rEpknH6L4aSf4bix7XJscOjsgjy8daKgIaQv0IStaGAbnWozxSfEx3o91A6uRZRVQXsZlmU0NrmLxmx3jw+DI7ZrSv8eDdCbdA4AgRxHtOkrXrgRsY1c0qkdTS3jHD4VOg0JhVdSjEgPhRjaZUZJcmQInf9IJTZyglgDgjjwLyAivQ+2mqxmrFirM8Y1+MwF87jy3Y+Iy5LzJGcfs1wUYSvKv11s6BVgh4SyCpJnW1QwNVVXVbsU1Nf+sPeNavD72mBC+ERrjiA3Q5c/r6mGQhu0aJ96EEIS7flKYeqGcMLLqLFBVf4hxfCg4HALrZPdyN2441E67LCOvenhnuf3voAwcFxCcfFdQoDocPmeLpaZf3qH0X6qgCL8r9458P+DMN7yGIf92yJYRGe7/+6o+rcGWoY15e6d2nShmnhxxkiXF0mnjVqnUy0mZhqtJTicH+ZObZaEMB3O3kTxE6TvnObBrS9v9rxz9Sl+VN32uv5bD2C+C2aiAH/FTatgnM4AbcO/FxYpXWCAg5aBKUGlsQv6ibvz4aDJwLWRDYW16IHv6sAltdw8ez3b4mbQFdcV0NiXU0JGdkr/pEjMoShKOy9gCA==
  template:
    metadata:
      name: forgejo-oidc-secret
      namespace: forgejo
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.authentik.clientSecret: AgBDgixM3u38DJK49TBdnpuipo0RGAGjHJXpSnphGgSvm1dSP8bpfvYxgtCIsarS/rDr3Bmnzzt0csbibzVyqHVLP7ukOnaC/P6FFvHZe3XWwHKI+RHmn16e9XIT/pPv84EbdT9B5olK7VgXp1kudeINmlDHKmrWkHJEh4pAYdHQrVbQ2iOl/FU1e2NUxzD4kBy7BPbgnGLc0iMHS4D80wxVIOet+ZhUBMJKsQ9WqGO9K4yTLL50uLPvIwdCvB0FSiqzl/uJ1+uc6qaw597fwOr8xWYvsR/aDODe0J8YaBBTHQ5OoKG4GERxAEm+ItwDI66zS7uhK30udOzrvIL+mkpjZujIJV3Qe/rARJk9ngGpttnI9s/s/MR5CllZRen4g/ZuqDur9e6cihvNj49pligor4b30MHwPGxUPjwq0YbaEggHbNhL9OMnUsjOfuCNzhv+pHZPL2AVjyZO3yPj+NCcCqAKtAIZ5drMVCd5DIyp6WQOA25xXIVN/g9+oZ/r30fDlT8+qZ6/SeuRKfPotDJkkgTMb2gWPVzXq4bbrdpauABfPHI5V0lnSV3KWbWdY4XsKWZfEDbfKR0cGdsiFI2KsAwcNreFp3Pj2/czLC4iQdXBocl2OyZzb5fOadqNCD4BzMetybKbbbkaz9067BzYsvLSvnRgXDmoaDsjonFuEPkJEKGn/q+Zu86hfNJD8rMptyV59UT1qw3qQZP01zPhx8qPf3S/iNBxJFY2kJ/vX4swddVOrhPrvZMkhUyhYp9T7Yn3GsSw7w==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc-secret
      namespace: argocd
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc-secret
  namespace: monitoring
spec:
  encryptedData:
    clientSecret: AgBRn6yz+okg4f3RWdDq5Z4aGKd9HiGwa7X+ImRFs5rLy4SzJf3NUbe7P3reSCyTE9MlnpAaVDhyJp7uRrjXJMT8WfFS9mCV6gUDNN9T6FuNOTRY7sjQPIVNksAsG/Ckz6Bqu4mxESiCiQrkQoMWmiN4CzABbrkqaMzzUHXFPPVUQmxZUwQaf8FQxuG1NXWevHAsapxxDgtE9jr/6N9gwIC/FtWxs4XByWNkL37/1GUH4QPPhgf9gpZgAkvmC09dkdPr+aw/xWtVXk6bbXHEDpGe/soq4n7++wtL6XtEUx170Dz8TuFoOSid63S3Iz4aSFCQjJDtp6foCReK3YH/Ru7tfoG+9ow80um6HZFsbLLkN6pJtaHFxJE4X1S066zZCY6Gh6utJ58RagcaDYidtp54iZIek9gjcxzaxxxGU/bMWFaBd4tv0cTLonAKi2/HGmkSJfxDcY1XsrpMOdc05IfNEHGqAGFmk7l91VVmjsucs0FQMd+TX5Qc5jQc9V/Z3n+1GjNYoO6xk2iq3yAYNWoDm/F5Z52BbHdL8E89F46XUNvsPo89E1aomW2F6KDs1l4wZPF8dKuavP+xAlkdfjnojrj6BJHUAm/bF70dm5eZ5mg7pFaCdYUKXPL/ActTVU9AjdPZtw/YEKKou7ADGdnPElVGIU6Vm6OqTYIwCSxTcVtWqsOyNWfzUmjLon3J6ww7Rq8AGb4Jtq/Iniy6Wu6PeaIJ/KlQam1PTAMmCSE4KxtvLOIe7ot6jZjTfHT8PAlRxUuPdp/mXQ==
  template:
    metadata:
      name: grafana-oidc-secret
      namespace: monitoring
