apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  scopes: '[groups]'
  policy.default: role:readonly
  policy.csv: |
    g, platform-admin, role:admin
    g, developer, role:readonly
    g, readonly, role:readonly
